name: RS2diffusion
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pytorch3d=0.7.0
  - numpy=1.23.3
  - py-opencv=4.6.0
  - zarr=2.12.0
  - tqdm=4.64.1
  - ipykernel=6.16
  - scikit-video=1.1.11
  - scikit-image=0.19.3
  - gym=0.21.0
  - pymunk=6.2.1
  - shapely=1.8.4
  - click=8.0.4
  - datasets=2.6.1
  - diffusers=0.18.2
  - huggingface_hub=0.21.3
  - llvm-openmp=14
  - pip:
    - pygame==2.1.2
